version: "3.8"

services:
  postgres:
    restart: always
    image: postgres:14.5
    expose:
      - 5432
    env_file:
      - app/app/.env
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  backend:
    restart: always
    container_name: kanban-board-backend
    build: ./app
    command: bash -c "
      python manage.py migrate &&
      gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    depends_on:
      - postgres
    volumes:
      - ./app/static:/app/static
      - ./app/media:/app/media

  nginx:
    restart: always
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend
    volumes:
      - ./app/static:/app/static:ro
      - ./app/media:/app/media:ro
