# Generated by Django 4.1.3 on 2023-09-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="Выполнена"),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Приоритет"),
        ),
    ]
