# Generated by Django 4.1.3 on 2023-09-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_is_completed_task_priority"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-due_at", "priority"],
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
    ]
